name: Release

on:
  push:
    tags-ignore:
      - testing_*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # submodules: recursive
          fetch-depth: 0
          fetch-tags: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.x.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Setup git
        run: |
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"

      - name: Install Versionize
        run: dotnet tool install --global Versionize
      - name: Versionize dry run
        run: versionize --dry-run
      - name: Versionize Release
        id: versionize
        run: versionize --exit-insignificant-commits
        continue-on-error: true
      - name: No release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping Release. No release required."
      - name: Retrieve version
        id: version
        shell: bash
        run: |
          echo "Retrieved version: $(versionize inspect)"
          echo "VERSION=$(versionize inspect)" >> "$GITHUB_OUTPUT"

      - name: Build
        if: steps.versionize.outcome == 'success'
        run: |
          invoke-expression 'dotnet build --no-restore --configuration Release --nologo'

      - name: Archive
        if: steps.versionize.outcome == 'success'
        run: Compress-Archive -Path AetherSenseRedux/bin/Release/* -DestinationPath AetherSenseRedux.zip
      - name: Upload a Build Artifact
        if: steps.versionize.outcome == 'success'
        uses: actions/upload-artifact@v4.4.3
        with:
          path: |
            ./AetherSenseRedux/bin/Release/*
      - name: Create Release
        if: steps.versionize.outcome == 'success'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: AetherSenseRedux ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./AetherSenseRedux.zip

      - name: Write out repo.json
        if: steps.versionize.outcome == 'success'
        run: |
          $ver = '${{ steps.version.outputs.VERSION }}'
          $path = './repo.json'
          $json = Get-Content -Raw $path | ConvertFrom-Json
          $json[0].AssemblyVersion = $ver
          $json[0].DownloadLinkInstall = $json.DownloadLinkInstall -replace '[^/]+/AetherSenseRedux.zip',"$ver/AetherSenseRedux.zip"
          $json[0].DownloadLinkUpdate = $json.DownloadLinkUpdate -replace '[^/]+/AetherSenseRedux.zip',"$ver/AetherSenseRedux.zip"
          $content = $json | ConvertTo-Json -AsArray
          set-content -Path $path -Value $content
      - name: Commit repo.json
        if: steps.versionize.outcome == 'success'
        run: |
          git add repo.json
          git commit --amend --no-edit || true
          git push --follow-tags origin main
